# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e4f39290a625ee3cfa4d7d08adacc8b59e6802474dc8b5210dd80f08302184aae3a801da007491283f79e57232db600866b9cf8801a6cf839c93546b4fc1b545

test:
  secret_key_base: 3560d5bfed832ad8e456472097642f79a4e26d3b343ea0a05101c80e8b85710d0f6e26997abbb927a496320c761c67dff7ab763f65863d547a568a9760a3fb25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
